# App Info
ios_app_id: 1446763654 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Unleaded # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: The best way to see the current price of gas on Ethereum.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Jeff Reiner
your_link: https://reiner.design
your_city:
email_address: jeff@reiner.design
facebook_username:
instagram_username:
twitter_username: mirshko
github_username: mirshko
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Know When To Fill Up
    description: "See how much your transaction will cost on the Ethereum network and how long it will take to complete in three speeds of gas (Slow, Average, and Fast)."
    fontawesome_icon_name: gas-pump

  - title: Save At The Pump
    description: "Quickly see the current price of Ethereum right at the top of the app. Easily change to your fiat currency of choice (currently USD, EUR, GBP, CAD, CNY)."
    fontawesome_icon_name: money-bill

  - title: Running On Empty?
    description: "Who's hogging the gas on the Ethereum network? See the top 10 consumers of gas across the whole network rated by percentage."
    fontawesome_icon_name: battery-empty

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#000"

# Not Used
cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#FF4F3C"
cover_overlay_transparency: 1

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "ffffff"

link_color: "#000"

app_title_color: "#000"
app_price_color: "#000"
app_description_color: "#000"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#666666"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
